// <copyright file="testrunTestsuiteTestsuiteTestsuiteTestcase.cs" company="Automate The Planet Ltd.">
// Copyright 2018 Automate The Planet Ltd.
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
// <author>Anton Angelov</author>
// <site>https://automatetheplanet.com/</site>

// <auto-generated/>
using System.Xml.Serialization;

namespace Meissa.Core.Model.NUnit
{
    [XmlType(AnonymousType = true)]
    public class testrunTestsuiteTestsuiteTestsuiteTestcase
    {
        private testrunTestsuiteTestsuiteTestsuiteTestcaseFailure _failureField;

        private testrunTestsuiteTestsuiteTestsuiteTestcaseAssertions _assertionsField;

        private string _idField;

        private string _nameField;

        private string _fullnameField;

        private string _methodnameField;

        private string _classnameField;

        private string _runstateField;

        private uint _seedField;

        private string _resultField;

        private string _starttimeField;

        private string _endtimeField;

        private decimal _durationField;

        private int _assertsField;

        public testrunTestsuiteTestsuiteTestsuiteTestcaseFailure failure
        {
            get => _failureField;
            set => _failureField = value;
        }

        public testrunTestsuiteTestsuiteTestsuiteTestcaseAssertions assertions
        {
            get => _assertionsField;
            set => _assertionsField = value;
        }

        [XmlAttribute]
        public string id
        {
            get => _idField;
            set => _idField = value;
        }

        [XmlAttribute]
        public string name
        {
            get => _nameField;
            set => _nameField = value;
        }

        [XmlAttribute]
        public string fullname
        {
            get => _fullnameField;
            set => _fullnameField = value;
        }

        [XmlAttribute]
        public string methodname
        {
            get => _methodnameField;
            set => _methodnameField = value;
        }

        [XmlAttribute]
        public string classname
        {
            get => _classnameField;
            set => _classnameField = value;
        }

        [XmlAttribute]
        public string runstate
        {
            get => _runstateField;
            set => _runstateField = value;
        }

        [XmlAttribute]
        public uint seed
        {
            get => _seedField;
            set => _seedField = value;
        }

        [XmlAttribute]
        public string result
        {
            get => _resultField;
            set => _resultField = value;
        }

        [XmlAttribute("start-time")]
        public string starttime
        {
            get => _starttimeField;
            set => _starttimeField = value;
        }

        [XmlAttribute("end-time")]
        public string endtime
        {
            get => _endtimeField;
            set => _endtimeField = value;
        }

        [XmlAttribute]
        public decimal duration
        {
            get => _durationField;
            set => _durationField = value;
        }

        [XmlAttribute]
        public int asserts
        {
            get => _assertsField;
            set => _assertsField = value;
        }
    }
}
